# Use the official Python image as the base image
FROM python:3.9

# Set the Working Dir in the container
WORKDIR /app

# Copy the python-app dependencies file to the container
COPY requirements.txt

# Install the python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the flask application code to the container
COPY app.py .

# Expose the port the Flask application will run on
EXPOSE 8000

# Command to run the python app when the container starts
CMD ["python", "app.py"]
